# NUMPY : PACKAGE FOR MULTIDIMENSIONAL ARRAY

    Handling with numerical data
    vector(1d)
    Matrrix(2d or 1d)

In [3]:
import numpy as np

### create numpy array

In [3]:
list1 = [1,2,3,4]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4])

In [4]:
listoflists = [[2,4,6],[3,6,9],[4,8,12],[5,10,15]]
np.array(listoflists)

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15]])

### generate array of series of numbers

In [5]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
np.arange(5,90,5) ## stepsize 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

In [7]:
np.zeros(10) ## array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(10,dtype = int) ## datatype integer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.zeros((3,4)) ## 3x4 matrix of each element 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones(10) ## array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(10,dtype = int) ## datatype integer

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.ones((5,4)) ## 5x4 matrix of each element 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.eye(6,dtype=int) ## Identity matrix

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [17]:
np.linspace(0,20,8) ## array of 8 numbers starting from 0 to 20 and each num are equally spaced

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

### generate of random numbers of array

In [20]:
np.random.rand(10) ## random numbers of U(0,1)

array([0.90115791, 0.09495586, 0.51923818, 0.21777647, 0.76062392,
       0.24353065, 0.27672265, 0.28864478, 0.59778681, 0.71897172])

In [22]:
np.random.randn(40) ## random numbers of N(0,1)

array([ 1.62322598,  0.99644298,  1.33135522, -0.80465839, -0.43569838,
        0.06122464,  0.40833449,  0.79355726,  0.16400121, -0.30986255,
       -0.05906672, -1.63408252, -2.13830064,  1.40486689,  0.24665355,
        0.64735097,  1.12078135, -1.11344768, -1.29877041,  0.46240974,
       -0.69845752,  1.02536636,  1.72195101, -1.73753789,  0.29064778,
        0.65891089, -0.58693009,  1.35681385, -1.684264  ,  0.60393208,
       -0.12392639, -0.99158791, -0.04218138,  1.75070264, -0.42425731,
        0.75521875, -1.74837988,  0.42031779, -0.27601184,  1.19942087])

In [32]:
np.random.randn(3,5) ## 3x5 random matrix

array([[ 0.11879222, -0.45571402,  0.55631413,  1.06700594,  0.99133189],
       [-0.76599271, -0.61938567,  0.13603116,  1.47135152,  0.54058056],
       [-0.19992971, -0.56748778, -1.78685421, -0.12049557,  0.9316098 ]])

In [29]:
np.random.randint(2,10) ## random integer between 2 to 10 

7

In [31]:
np.random.randint(1,45,50) ## 50 random integer between 1 to 45

array([42, 25, 34, 27, 37, 18, 29, 28, 30, 43, 19, 43, 25, 31, 34,  1, 26,
       44, 37, 15, 32,  9, 24, 15, 19,  2, 23,  2, 11, 11, 30, 29, 43, 14,
        7, 18, 32,  3, 34,  2, 32,  6, 21, 40, 33,  7, 27, 12,  6, 29])

### summary of array or matrix

In [43]:
randarr = np.random.randn(10)
randarr

array([ 1.28482449,  0.13145662,  0.38477854,  0.20872881,  1.2369058 ,
        0.55139906, -0.91520776,  0.51197089,  0.58649566,  2.12921979])

In [44]:
randarr.min() # minimum

-0.9152077569123801

In [45]:
randarr.max() # maximum

2.129219786068574

In [46]:
randarr.argmin() # index of minimum value

6

In [47]:
randarr.argmax() # index of maximum value

9

In [56]:
randarr.dtype # datatype of randarr

dtype('float64')

In [57]:
randarr.shape

(10,)

In [62]:
randarr.reshape(2,5)

array([[ 1.28482449,  0.13145662,  0.38477854,  0.20872881,  1.2369058 ],
       [ 0.55139906, -0.91520776,  0.51197089,  0.58649566,  2.12921979]])

### Accessing elements of a array(SLICING)

In [72]:
sarr = np.arange(11,21)
sarr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
sarr[0]

11

In [74]:
sarr[1]

12

In [75]:
sarr[1:5]

array([12, 13, 14, 15])

In [79]:
sarr[[1,5]]

array([12, 16])

In [76]:
sarr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [77]:
sarr[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [81]:
sarr[1] = 21 ## Change the elements of index 1
sarr

array([11, 21, 13, 14, 15, 16, 17, 18, 19, 20])

## Multidimensional array


In [7]:
Multi_arr = np.array(([12,22,32,42],[13,23,33,43],[14,24,34,44]))
Multi_arr

array([[12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

## Accessing elements

In [8]:
Multi_arr[0,2]

32

In [9]:
Multi_arr[0][2]

32

In [20]:
Multi_arr[1,:]

array([13, 23, 33, 43])

In [18]:
Multi_arr[:,(2,3)]

array([[32, 42],
       [33, 43],
       [34, 44]])

In [24]:
Multi_arr[0]

array([12, 22, 32, 42])

In [26]:
Multi_arr[1:3]

array([[13, 23, 33, 43],
       [14, 24, 34, 44]])

In [32]:
Multi_arr[(0,2),:]

array([[12, 22, 32, 42],
       [14, 24, 34, 44]])

## Selection techniques

In [42]:
s_arr2 = np.arange(3,21)
s_arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [43]:
bool = s_arr2 < 5
bool

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [44]:
s_arr2[bool]

array([3, 4])

## General Arithmetic

In [45]:
np.sqrt(s_arr2)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
       3.60555128, 3.74165739, 3.87298335, 4.        , 4.12310563,
       4.24264069, 4.35889894, 4.47213595])

In [46]:
np.exp(s_arr2)

array([2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02,
       1.09663316e+03, 2.98095799e+03, 8.10308393e+03, 2.20264658e+04,
       5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
       1.78482301e+08, 4.85165195e+08])

In [47]:
np.log(s_arr2)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015,
       2.07944154, 2.19722458, 2.30258509, 2.39789527, 2.48490665,
       2.56494936, 2.63905733, 2.7080502 , 2.77258872, 2.83321334,
       2.89037176, 2.94443898, 2.99573227])

In [52]:
np.square(s_arr2)

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225,
       256, 289, 324, 361, 400], dtype=int32)

In [48]:
np.max(s_arr2)

20

In [49]:
np.min(s_arr2)

3

In [50]:
np.argmin(s_arr2)

0

In [51]:
np.argmax(s_arr2)

17

In [53]:
np.std(s_arr2)

5.188127472091127

In [54]:
np.var(s_arr2)

26.916666666666668

In [55]:
np.mean(s_arr2)

11.5

In [57]:
s_arr3 = np.random.randn(4,5)
s_arr3

array([[ 1.03160011,  0.40346316,  0.22471921,  0.97894864, -0.14690952],
       [ 0.06078662,  1.80237094, -0.6852189 , -1.566897  , -0.56912932],
       [-1.9223958 , -0.31445896,  0.43554305,  0.76446581,  1.328348  ],
       [ 0.38657684,  0.68479626, -2.02374858, -1.28596108, -0.39502091]])

In [58]:
np.round(s_arr3,decimals=2)

array([[ 1.03,  0.4 ,  0.22,  0.98, -0.15],
       [ 0.06,  1.8 , -0.69, -1.57, -0.57],
       [-1.92, -0.31,  0.44,  0.76,  1.33],
       [ 0.39,  0.68, -2.02, -1.29, -0.4 ]])

In [60]:
fruits=np.array(["banana","orange","apple","orange"])
np.unique(fruits)

array(['apple', 'banana', 'orange'], dtype='<U6')