# Numpy: Package for Multidimensional array
    Handling with numerical data
    Vector(1d)
    Matrix(2d or 1d)

In [1]:
import numpy as np

In [2]:
sample_list = [6,7,9]
np.array(sample_list)

array([6, 7, 9])

In [3]:
arr = np.array([6,7,9])
arr

array([6, 7, 9])

In [4]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(19,32)

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [7]:
np.arange(21,77,5) ## step size 5

array([21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((3,4)) ##3 x 4 matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.linspace(0,11,6)

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

In [17]:
np.linspace(10,50,10)

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [18]:
np.eye(5,dtype = int) ## Identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.random.rand(3,4) ## 3 x 4 of Random values of U(0,1) 

array([[0.14844381, 0.97618652, 0.19785342, 0.59422753],
       [0.8038288 , 0.48080016, 0.26841333, 0.60958033]])

In [20]:
np.random.randn(3,6) ## Negative num included 3x6 of random values of Normal dist 

array([[-0.97591596, -0.14865667, -0.48503525,  0.11476461,  0.51724232,
         1.37449602],
       [-0.21693181,  0.57074979, -0.02738065,  1.32828116,  1.42288329,
         0.78329965],
       [-1.60482235,  0.51342259,  0.89986023, -0.60207975, -0.36658614,
        -2.35211277]])

In [31]:
np.random.randint(5,23,23) ## Random 23 integers from 5 to 23

array([17, 12,  9,  7,  8, 17,  6,  8,  6, 14,  8,  9, 12, 21, 17,  6, 20,
       20, 12,  7, 15, 12,  8])